set(CPACK_PACKAGE_CONTACT "cppinclude@yandex.com")
set(CPACK_PACKAGE_DESCRIPTION "")
set(CPACK_PACKAGE_VENDOR "cppinclude")

set(CPACK_DEBIAN_PACKAGE_NAME "${PROJECT_NAME}-${CMAKE_HOST_SYSTEM_PROCESSOR}-${CMAKE_PROJECT_VERSION}")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER ${CPACK_PACKAGE_CONTACT} )
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

if(NOT DEFINED CMAKE_INSTALL_PREFIX AND NOT WIN32)
	set(CMAKE_INSTALL_PREFIX "/usr/bin/")
endif()

install(TARGETS ${PROJECT_NAME} RUNTIME DESTINATION bin)
